---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.6"
services:
  db:
    image: "postgres:9.6.9-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/dev.env
    ports:
      - "5432:5432"

  web:
    <<: &web
      build: .
      volumes:
        - .:/code
        - django-static:/var/www/django/static
      depends_on:
        - db
      networks:
        - webnet
        - proxynet
      env_file: ./config/dev.env
      environment:
        DJANGO_DATABASE_HOST: db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./docker-entrypoint.sh'

# This task is an example of how to extend existing ones:
# some_worker:
#   <<: *web
#   command: python manage.py worker_process

networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:
  # Network for your internals, use it by default:
  webnet:

volumes:
  pgdata:
  django-static:
  django-media: