name: glycemic-patterns-webapp
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- _license=1.1=py36_1
- anaconda=4.3.1=np111py36_0
- anaconda-client=1.6.0=py36_0
- anaconda-navigator=1.5.0=py36_0
- anaconda-project=0.4.1=py36_0
- astroid=1.4.9=py36_0
- backports=1.0=py36_0
- bitarray=0.8.1=py36_0
- blaze=0.10.1=py36_0
- boto=2.45.0=py36_0
- cairo=1.14.8=0
- cffi=1.9.1=py36_0
- cloudpickle=0.2.2=py36_0
- clyent=1.2.2=py36_0
- configobj=5.0.6=py36_0
- cryptography=1.7.1=py36_0
- datashape=0.5.4=py36_0
- dill=0.2.5=py36_0
- et_xmlfile=1.0.1=py36_0
- fastcache=1.0.2=py36_1
- flask-cors=3.0.2=py36_0
- fontconfig=2.12.1=2
- freetype=2.5.5=2
- get_terminal_size=1.0.0=py36_0
- gevent=1.2.1=py36_0
- glib=2.50.2=1
- graphviz=2.38.0=4
- greenlet=0.4.11=py36_0
- h5py=2.6.0=np111py36_2
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py36_1
- icu=54.1=0
- idna=2.2=py36_0
- ipython=5.1.0=py36_0
- ipywidgets=5.2.2=py36_1
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jedi=0.9.0=py36_1
- jinja2=2.9.4=py36_0
- jupyter=1.0.0=py36_3
- libgcc=4.8.5=2
- libgfortran=3.0.0=1
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxml2=2.9.4=0
- llvmlite=0.15.0=py36_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np111py36_0
- mistune=0.7.3=py36_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py36_3
- mpmath=0.19=py36_1
- nbconvert=4.2.0=py36_0
- nose=1.3.7=py36_1
- notebook=4.3.1=py36_0
- numba=0.30.1=np111py36_0
- numexpr=2.6.1=np111py36_2
- numpy=1.11.3=py36_0
- odo=0.5.0=py36_1
- openpyxl=2.4.1=py36_0
- openssl=1.0.2k=1
- pango=1.40.3=1
- path.py=10.0=py36_0
- pathlib2=2.2.0=py36_0
- pcre=8.39=1
- pickleshare=0.7.4=py36_0
- pillow=4.0.0=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.9=py36_0
- pyasn1=0.1.9=py36_0
- pycosat=0.6.1=py36_1
- pycrypto=2.6.1=py36_4
- pycurl=7.43.0=py36_2
- pygments=2.1.3=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- qt=5.6.2=3
- qtawesome=0.4.3=py36_0
- qtconsole=4.2.1=py36_1
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py36_0
- rope=0.9.4=py36_1
- ruamel_yaml=0.11.14=py36_1
- scikit-learn=0.18.1=np111py36_1
- scipy=0.18.1=np111py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sockjs-tornado=1.0.3=py36_0
- spyder=3.1.2=py36_0
- statsmodels=0.6.1=np111py36_1
- tk=8.5.18=0
- unicodecsv=0.14.1=py36_0
- werkzeug=0.11.15=py36_0
- widgetsnbextension=1.2.6=py36_0
- xlsxwriter=0.9.6=py36_0
- xlwt=1.2.0=py36_0
- xz=5.2.2=1
- alabaster=0.7.9=py36_0
- astropy=1.3=np111py36_0
- babel=2.3.4=py36_0
- beautifulsoup4=4.5.3=py36_0
- bidict=0.13.0=py36_0
- bokeh=0.12.4=py36_0
- bottleneck=1.2.0=np111py36_0
- ca-certificates=2017.1.23=0
- certifi=2017.1.23=py36_0
- chardet=2.3.0=py36_0
- chest=0.2.3=py36_0
- click=6.7=py36_0
- colorama=0.3.7=py36_0
- contextlib2=0.5.4=py36_0
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- cython=0.25.2=py36_0
- cytoolz=0.8.2=py36_0
- dask=0.13.0=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.2=py36_0
- expat=2.1.0=0
- flask=0.12=py36_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- imagesize=0.7.1=py36_0
- ipykernel=4.5.2=py36_0
- ipython_genutils=0.1.0=py36_0
- isort=4.2.5=py36_0
- jdcal=1.3=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- lazy-object-proxy=1.2.2=py36_0
- libffi=3.2.1=1
- libiconv=1.14=0
- libsodium=1.0.10=0
- libxcb=1.12=1
- libxslt=1.1.29=0
- locket=0.2.0=py36_1
- lxml=3.7.2=py36_0
- mccabe=0.6.1=py36_0
- multipledispatch=0.4.9=py36_0
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- networkx=1.11=py36_0
- nltk=3.2.2=py36_0
- numpydoc=0.6.0=py36_0
- pandas=0.19.2=np111py36_1
- partd=0.3.7=py36_0
- patsy=0.4.1=py36_0
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- pixman=0.34.0=0
- ply=3.9=py36_0
- psutil=5.0.1=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.32=py36_0
- pycparser=2.17=py36_0
- pyflakes=1.5.0=py36_0
- pylint=1.6.4=py36_1
- pyopenssl=16.2.0=py36_0
- pytables=3.3.0=np111py36_0
- pytest=3.0.5=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qtpy=1.2.1=py36_0
- requests=2.12.4=py36_0
- scikit-image=0.12.3=np111py36_1
- seaborn=0.7.1=py36_0
- singledispatch=3.4.0.3=py36_0
- snowballstemmer=1.2.1=py36_0
- sphinx=1.5.1=py36_0
- sqlalchemy=1.1.5=py36_0
- sqlite=3.13.0=0
- sympy=1.0=py36_0
- terminado=0.6=py36_0
- toolz=0.8.2=py36_0
- tornado=4.4.2=py36_0
- traitlets=4.3.1=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- wrapt=1.10.8=py36_0
- xlrd=1.0.0=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- setuptools=27.2.0=py36_0
- pip:
  - appdirs==1.4.3
  - backports.shutil-get-terminal-size==1.0.0
  - cairocffi==0.8.0
  - cairosvg==2.0.2
  - cssselect==1.0.1
  - django==1.10.6
  - django-admin-bootstrapped==2.5.7
  - django-authtools==1.5.0
  - django-braces==1.11.0
  - django-crispy-forms==1.6.1
  - django-debug-toolbar==1.7
  - django-environ==0.4.1
  - django-multiselectfield==0.1.5
  - easy-thumbnails==2.3
  - et-xmlfile==1.0.1
  - html5lib==0.999999999
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - olefile==0.44
  - packaging==16.8
  - "git+https://github.com/nlhepler/pydot.git#egg=pydot"
  - prompt-toolkit==1.0.9
  - pyphen==0.9.4
  - rope-py3k==0.9.4.post1
  - sqlparse==0.2.3
  - tables==3.3.0
  - tinycss==0.4
  - weasyprint==0.36
  - webencodings==0.5.1
