name: glycemic-patterns-webapp
channels:
- defaults
dependencies:
- openssl=1.0.2k=1
- pip=9.0.1=py34_1
- python=3.4.5=0
- readline=6.2=2
- setuptools=27.2.0=py34_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - django==1.10.6
  - django-admin-bootstrapped==2.5.7
  - django-authtools==1.5.0
  - django-braces==1.11.0
  - django-crispy-forms==1.6.1
  - django-debug-toolbar==1.7
  - django-environ==0.4.1
  - django-multiselectfield==0.1.5
  - easy-thumbnails==2.3
  - olefile==0.44
  - pillow==4.0.0
  - six==1.10.0
  - sqlparse==0.2.3
  - werkzeug==0.12.1
