# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tfg_webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=tfg_webapp.models.generate_filename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg_webapp.ReportSettings'),
        ),
    ]
