# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import tfg_webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=tfg_webapp.models.generate_filename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('columns', multiselectfield.db.fields.MultiSelectField(choices=[('Mean', 'Mean'), ('Std', 'Standard deviation'), ('Max', 'Maximum'), ('Min', 'Minimum'), ('MAGE', 'MAGE')], default='Mean,Std,Max,Min,MAGE', max_length=21)),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg_webapp.ReportSettings'),
        ),
    ]
